# Use postgres/example user/password credentials
version: '3.9'

services:

  intgration-db:
    image: postgres
    container_name: integration-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5441:5432
    volumes:
      - integration-db:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      # For streams
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream advertised_host localhost
    ports:
      - "5672:5672"
      # For streams
      - "5552:5552"
      - "15672:15672"
    volumes:
      - ${PWD}/enabled_plugins:/etc/rabbitmq/enabled_plugins

volumes:
  integration-db: